### ISSUE TITLE
scABC2

### ISSUE THREAD

**Issue by leeanapeters** [abcwcm/GeartySchietinger#1]
Hi there, where are you sourcing scABC2 from?
This seems like a helpful package but I am unable to find it.

Thanks!

Leeana

**Comment by friedue** [comment]
Sorry for the late reply, need to change the alert settings here!

scABC2 is my personal, in-house collection of scripts, mostly for visualization; I thought I had exported most functions that I relied on in the `src` directory, but now I see that I missed a couple. Most functionalities are equally well served by the [dittoSeq package](https://bioconductor.org/packages/release/bioc/html/dittoSeq.html), which has the added benefit of being more tolerant of Seurat objects than my own scripts.
